spring:
  security:
    jwt:
      secret: "YW5kcmVpc29ueWFwaXRlcjIwMjVmZWI="
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://customer-service
          predicates:
            - Path=/api/v1/customers/**

        - id: order-service
          uri: lb:http://order-service
          predicates:
            - Path=/api/v1/orders/**

        - id: product-service
          uri: lb:http://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: auth-service
          uri: lb:http://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
            - AddRequestHeader=Authorization, Basic ZXVyZWthOnBhc3N3b3Jk

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - AddRequestHeader=Authorization, Basic ZXVyZWthOnBhc3N3b3Jk

server:
  port: 8111

application:
  config:
    auth-url: http://auth-service/api/v1/auth
