eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
