spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/customer_service
    username: ttsk
    password: ttsk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0
